import type { ProtocolDefinition } from '@/lib/protocol-types'

export const IEC61730_PROTOCOLS: ProtocolDefinition[] = [
  {
    id: 'mst11',
    code: 'MST 11',
    name: 'Visual Inspection (Safety)',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '10.1',
    category: 'visual',
    duration: '1h',
    sequence: 1,
    critical: false,
    description: 'Safety-focused visual inspection per IEC 61730-2:2023 MST 11.',
    documentFormatNumber: 'SLX-FMT-61730-MST11-001',
    revision: '01',
    equipment: ['Lightbox', 'Magnifier 10×', 'Camera'],
    testConditions: [
      { label: 'Illumination', value: '≥ 1000', unit: 'lux', source: 'IEC 61730-2:2023 MST 11' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst11-1', parameter: 'Accessible live parts', operator: 'manual', limit: 'None', unit: '-', critical: true, description: 'No accessible live parts' },
      { id: 'ac-mst11-2', parameter: 'Sharp edges', operator: 'manual', limit: 'None accessible', unit: '-', critical: false, description: 'No sharp edges accessible to users' },
      { id: 'ac-mst11-3', parameter: 'Labels and markings', operator: 'manual', limit: 'All present and legible', unit: '-', critical: false, description: 'All required safety markings present' },
    ],
    measurements: [
      { id: 'm-mst11-1', label: 'Accessible live parts found', unit: '-', type: 'boolean', required: true, criterionId: 'ac-mst11-1' },
      { id: 'm-mst11-2', label: 'Sharp edges found', unit: '-', type: 'boolean', required: true, criterionId: 'ac-mst11-2' },
      { id: 'm-mst11-3', label: 'Safety labels present and legible', unit: '-', type: 'boolean', required: true, criterionId: 'ac-mst11-3' },
      { id: 'm-mst11-4', label: 'Observations', unit: '-', type: 'textarea', required: false },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst12',
    code: 'MST 12',
    name: 'Continuity of Protective Earth Bonding',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '10.2',
    category: 'safety',
    duration: '1h',
    sequence: 2,
    critical: true,
    description: 'Test of the earth bonding continuity for modules with class II or grounded frames per IEC 61730-2 MST 12.',
    documentFormatNumber: 'SLX-FMT-61730-MST12-001',
    revision: '01',
    equipment: ['Milliohm meter or bond tester', 'Test probes'],
    testConditions: [
      { label: 'Test current', value: '25 ± 2.5', unit: 'A', source: 'IEC 61730-2:2023 MST 12' },
      { label: 'Test duration', value: '60', unit: 's', source: 'IEC 61730-2:2023 MST 12' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst12-1', parameter: 'Bonding resistance', operator: 'lte', limit: '0.1 Ω', limitValue: 0.1, unit: 'Ω', critical: true, description: 'Earth bonding resistance ≤ 0.1 Ω' },
    ],
    measurements: [
      { id: 'm-mst12-1', label: 'Bonding resistance measured', unit: 'Ω', type: 'number', required: true, criterionId: 'ac-mst12-1', min: 0 },
      { id: 'm-mst12-2', label: 'Test current applied', unit: 'A', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst13',
    code: 'MST 13',
    name: 'Impulse Voltage Test',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '10.3',
    category: 'safety',
    duration: '1h',
    sequence: 3,
    critical: true,
    description: 'High-voltage impulse test to evaluate dielectric withstand per IEC 61730-2 MST 13.',
    documentFormatNumber: 'SLX-FMT-61730-MST13-001',
    revision: '01',
    equipment: ['Impulse voltage generator', 'High-voltage probes', 'Safety cage'],
    testConditions: [
      { label: 'Impulse voltage (SYS I)', value: '3000', unit: 'V peak', source: 'IEC 61730-2:2023 MST 13' },
      { label: 'Impulse voltage (SYS II)', value: '6000', unit: 'V peak', source: 'IEC 61730-2:2023 MST 13' },
      { label: 'Waveform', value: '1.2/50 μs', unit: '-', source: 'IEC 61230-2:2023 MST 13' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst13-1', parameter: 'Dielectric withstand', operator: 'manual', limit: 'No breakdown or flashover', unit: '-', critical: true, description: 'No breakdown or flashover during impulse' },
    ],
    measurements: [
      { id: 'm-mst13-1', label: 'Applied impulse voltage', unit: 'V peak', type: 'number', required: true },
      { id: 'm-mst13-2', label: 'Breakdown/flashover observed', unit: '-', type: 'boolean', required: true, criterionId: 'ac-mst13-1' },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst14',
    code: 'MST 14',
    name: 'Wet Hi-Pot Test',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '10.4',
    category: 'safety',
    duration: '2h',
    sequence: 4,
    critical: true,
    description: 'Wet insulation withstand test: module wetted with surfactant, high AC voltage applied between circuit and frame.',
    documentFormatNumber: 'SLX-FMT-61730-MST14-001',
    revision: '01',
    equipment: ['AC hipot tester', 'Surfactant solution', 'Safety equipment'],
    testConditions: [
      { label: 'Test voltage (SYS I, Vsys ≤ 600V)', value: '2 × Vsys + 1000', unit: 'VAC', source: 'IEC 61730-2:2023 MST 14' },
      { label: 'Test duration', value: '60', unit: 's', source: 'IEC 61730-2:2023 MST 14' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst14-1', parameter: 'Dielectric withstand (wet)', operator: 'manual', limit: 'No breakdown', unit: '-', critical: true, description: 'No dielectric breakdown or flashover while wet' },
    ],
    measurements: [
      { id: 'm-mst14-1', label: 'Test voltage applied', unit: 'VAC', type: 'number', required: true },
      { id: 'm-mst14-2', label: 'Leakage current', unit: 'mA', type: 'number', required: true },
      { id: 'm-mst14-3', label: 'Breakdown observed', unit: '-', type: 'boolean', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst21',
    code: 'MST 21',
    name: 'Module Breakage Test',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '11.1',
    category: 'mechanical',
    duration: '2h',
    sequence: 5,
    critical: false,
    description: 'Test for module behavior under breakage conditions (applicable to thin glass or flexible modules).',
    documentFormatNumber: 'SLX-FMT-61730-MST21-001',
    revision: '01',
    equipment: ['Impact weight / drop test apparatus', 'Safety gloves', 'Camera'],
    testConditions: [
      { label: 'Impact energy', value: 'Per class', unit: 'J', source: 'IEC 61730-2:2023 MST 21' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst21-1', parameter: 'Live parts accessible after breakage', operator: 'manual', limit: 'None', unit: '-', critical: true, description: 'No live parts accessible after simulated breakage' },
    ],
    measurements: [
      { id: 'm-mst21-1', label: 'Impact energy applied', unit: 'J', type: 'number', required: true },
      { id: 'm-mst21-2', label: 'Live parts accessible after test', unit: '-', type: 'boolean', required: true },
      { id: 'm-mst21-3', label: 'Fragmentation pattern', unit: '-', type: 'textarea', required: false },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst22',
    code: 'MST 22',
    name: 'Cut Susceptibility Test',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '11.2',
    category: 'mechanical',
    duration: '1h',
    sequence: 6,
    critical: false,
    description: 'Test to check wiring insulation resistance to cuts and abrasion per IEC 61730-2 MST 22.',
    documentFormatNumber: 'SLX-FMT-61730-MST22-001',
    revision: '01',
    equipment: ['Cut susceptibility jig', 'Razor blade', 'Insulation tester'],
    testConditions: [
      { label: 'Force applied', value: '2', unit: 'N', source: 'IEC 61730-2:2023 MST 22' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst22-1', parameter: 'Insulation after cut test', operator: 'manual', limit: 'No electrical contact', unit: '-', critical: true, description: 'No electrical contact to active conductor after cut' },
    ],
    measurements: [
      { id: 'm-mst22-1', label: 'Electrical contact through insulation', unit: '-', type: 'boolean', required: true },
      { id: 'm-mst22-2', label: 'Observations', unit: '-', type: 'textarea', required: false },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst23',
    code: 'MST 23',
    name: 'Scratch Test on Encapsulant',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '11.3',
    category: 'mechanical',
    duration: '1h',
    sequence: 7,
    critical: false,
    description: 'Scratch resistance test on module front surface to verify encapsulant protection.',
    documentFormatNumber: 'SLX-FMT-61730-MST23-001',
    revision: '01',
    equipment: ['Scratch hardness tester'],
    testConditions: [],
    acceptanceCriteria: [
      { id: 'ac-mst23-1', parameter: 'Scratch depth', operator: 'manual', limit: 'Does not penetrate to cells', unit: '-', critical: false, description: 'Scratch does not expose active circuit' },
    ],
    measurements: [
      { id: 'm-mst23-1', label: 'Scratch penetrates to cell layer', unit: '-', type: 'boolean', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst24',
    code: 'MST 24',
    name: 'Bypass Diode Test (Safety)',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '11.4',
    category: 'safety',
    duration: '4h',
    sequence: 8,
    critical: true,
    description: 'Safety test of bypass diode failure mode under maximum forward current stress.',
    documentFormatNumber: 'SLX-FMT-61730-MST24-001',
    revision: '01',
    equipment: ['Solar simulator', 'IR camera', 'Thermocouple on JB'],
    testConditions: [
      { label: 'Irradiance', value: '1000', unit: 'W/m²', source: 'IEC 61730-2:2023 MST 24' },
      { label: 'Duration per diode', value: '1 + 1', unit: 'h (hot + cold cycle)', source: 'IEC 61730-2:2023 MST 24' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst24-1', parameter: 'Fire or explosion', operator: 'manual', limit: 'None', unit: '-', critical: true, description: 'No fire or explosion during diode failure mode test' },
      { id: 'ac-mst24-2', parameter: 'Toxic gas emission', operator: 'manual', limit: 'None hazardous', unit: '-', critical: true, description: 'No hazardous gas emitted' },
    ],
    measurements: [
      { id: 'm-mst24-1', label: 'Fire or explosion observed', unit: '-', type: 'boolean', required: true },
      { id: 'm-mst24-2', label: 'Toxic emissions observed', unit: '-', type: 'boolean', required: true },
      { id: 'm-mst24-3', label: 'Max JB temperature', unit: '°C', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst25',
    code: 'MST 25',
    name: 'Thermal Test (Safety)',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '11.5',
    category: 'safety',
    duration: '2h',
    sequence: 9,
    critical: false,
    description: 'Thermal test on junction box under maximum power conditions to verify temperature ratings.',
    documentFormatNumber: 'SLX-FMT-61730-MST25-001',
    revision: '01',
    equipment: ['Solar simulator', 'Thermocouple', 'IR camera'],
    testConditions: [
      { label: 'Irradiance', value: '1000', unit: 'W/m²', source: 'IEC 61730-2:2023 MST 25' },
      { label: 'Ambient temperature', value: '25 ± 5', unit: '°C', source: 'IEC 61730-2:2023 MST 25' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst25-1', parameter: 'JB temperature vs T-rating', operator: 'lte', limit: 'T-rating of JB material', unit: '°C', critical: true, description: 'JB temperature does not exceed rated temperature of materials' },
    ],
    measurements: [
      { id: 'm-mst25-1', label: 'Max JB/connector temperature', unit: '°C', type: 'number', required: true, criterionId: 'ac-mst25-1' },
      { id: 'm-mst25-2', label: 'JB material T-rating', unit: '°C', type: 'number', required: true },
      { id: 'm-mst25-3', label: 'Ambient temperature at test', unit: '°C', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mst26',
    code: 'MST 26',
    name: 'Glow Wire Test',
    standard: 'IEC 61730',
    standardYear: '2023',
    clause: '11.6',
    category: 'safety',
    duration: '1h',
    sequence: 10,
    critical: false,
    description: 'Glow wire flammability test on plastic parts per IEC 61730-2 MST 26 / IEC 60695-2-12.',
    documentFormatNumber: 'SLX-FMT-61730-MST26-001',
    revision: '01',
    equipment: ['Glow wire test apparatus (per IEC 60695-2-12)', 'Thermocouple', 'Wrapping paper layer'],
    testConditions: [
      { label: 'Glow wire temperature', value: '650 – 850', unit: '°C (per application class)', source: 'IEC 60695-2-12' },
      { label: 'Application duration', value: '30', unit: 's', source: 'IEC 60695-2-12' },
    ],
    acceptanceCriteria: [
      { id: 'ac-mst26-1', parameter: 'Flame/glowing extinguish time after removal', operator: 'lte', limit: '30 s', limitValue: 30, unit: 's', critical: true, description: 'Any flames/glowing extinguish within 30 s after glow wire removal' },
    ],
    measurements: [
      { id: 'm-mst26-1', label: 'Glow wire temperature applied', unit: '°C', type: 'number', required: true },
      { id: 'm-mst26-2', label: 'Time to extinguish after removal', unit: 's', type: 'number', required: true, criterionId: 'ac-mst26-1' },
      { id: 'm-mst26-3', label: 'Test material/component', unit: '-', type: 'text', required: true },
    ],
    hasIVCurve: false,
  },
]
