import type { ProtocolDefinition } from '@/lib/protocol-types'

export const IEC61853_PROTOCOLS: ProtocolDefinition[] = [
  {
    id: 'iec61853-p1',
    code: 'IEC 61853 P1',
    name: 'Power & Efficiency Matrix (Irradiance/Temperature)',
    standard: 'IEC 61853',
    standardYear: '2011',
    clause: '5',
    category: 'electrical',
    duration: '16h',
    sequence: 1,
    critical: true,
    description: 'I-V measurements at multiple irradiance (100–1100 W/m²) and temperature (15–75°C) combinations to build performance matrix per IEC 61853-1.',
    documentFormatNumber: 'SLX-FMT-61853-P1-001',
    revision: '01',
    equipment: ['Flash tester (variable irradiance or ND filters)', 'Temperature-controlled mounting plate', 'Reference cell', 'Pt100 sensors'],
    testConditions: [
      { label: 'Irradiance levels', value: '100, 200, 400, 600, 800, 1000, 1100', unit: 'W/m²', source: 'IEC 61853-1:2011 Table 1' },
      { label: 'Temperature levels', value: '15, 25, 50, 75', unit: '°C', source: 'IEC 61853-1:2011 Table 1' },
      { label: 'Spectrum', value: 'AM1.5G (IEC 60904-3)', unit: '-', source: 'IEC 60904-3' },
    ],
    acceptanceCriteria: [
      { id: 'ac-853p1-1', parameter: 'STC Pmax consistency', operator: 'between', limit: '±3% of MQT 10.2 result', unit: '%', critical: true, description: 'STC power consistent with MQT 10.2 measurement' },
      { id: 'ac-853p1-2', parameter: 'Low irradiance performance', operator: 'gte', limit: 'η(200)/η(1000) ≥ 0.95', unit: '-', critical: false, description: 'Efficiency ratio at low irradiance meets threshold' },
    ],
    measurements: [
      { id: 'm-853p1-1', label: 'Pmax at 1000 W/m², 25°C (STC)', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-853p1-2', label: 'Pmax at 800 W/m², 25°C', unit: 'W', type: 'number', required: true },
      { id: 'm-853p1-3', label: 'Pmax at 600 W/m², 25°C', unit: 'W', type: 'number', required: true },
      { id: 'm-853p1-4', label: 'Pmax at 400 W/m², 25°C', unit: 'W', type: 'number', required: true },
      { id: 'm-853p1-5', label: 'Pmax at 200 W/m², 25°C', unit: 'W', type: 'number', required: true },
      { id: 'm-853p1-6', label: 'Pmax at 1000 W/m², 50°C', unit: 'W', type: 'number', required: true },
      { id: 'm-853p1-7', label: 'Pmax at 1000 W/m², 75°C', unit: 'W', type: 'number', required: true },
      { id: 'm-853p1-8', label: 'Efficiency at STC', unit: '%', type: 'number', required: true, autoFillFrom: 'efficiency' },
    ],
    rawDataConfig: {
      type: 'flasher_iv',
      description: 'Flash tester multi-condition CSV',
      acceptedFormats: ['.csv', '.xlsx'],
      columnMapping: { voltage: ['V', 'Voltage'], current: ['I', 'Current'], pmax: ['Pmax'], voc: ['Voc'], isc: ['Isc'], irradiance: ['G', 'Irr'], cellTemp: ['Tc', 'Temp'] },
    },
    hasIVCurve: true,
  },

  {
    id: 'iec61853-p2',
    code: 'IEC 61853 P2',
    name: 'Spectral Response & Angle of Incidence',
    standard: 'IEC 61853',
    standardYear: '2016',
    clause: '5',
    category: 'electrical',
    duration: '4h',
    sequence: 2,
    critical: false,
    description: 'Relative spectral response measurement and angular dependence of irradiance per IEC 61853-2.',
    documentFormatNumber: 'SLX-FMT-61853-P2-001',
    revision: '01',
    equipment: ['Spectroradiometer', 'Monochromatic light source', 'Lock-in amplifier', 'Angular positioning fixture'],
    testConditions: [
      { label: 'Spectral range', value: '300–1200', unit: 'nm', source: 'IEC 61853-2:2016' },
      { label: 'AOI range', value: '0 to 80°', unit: 'degrees', source: 'IEC 61853-2:2016' },
    ],
    acceptanceCriteria: [
      { id: 'ac-853p2-1', parameter: 'Spectral response consistency', operator: 'manual', limit: 'Match model within ±5%', unit: '%', critical: false, description: 'Measured SR consistent with manufacturer model' },
    ],
    measurements: [
      { id: 'm-853p2-1', label: 'Peak spectral response wavelength', unit: 'nm', type: 'number', required: false },
      { id: 'm-853p2-2', label: 'IAM at 60°', unit: '-', type: 'number', required: true },
      { id: 'm-853p2-3', label: 'IAM at 80°', unit: '-', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'iec61853-p3',
    code: 'IEC 61853 P3',
    name: 'Energy Rating Calculation',
    standard: 'IEC 61853',
    standardYear: '2018',
    clause: '8',
    category: 'electrical',
    duration: '4h',
    sequence: 3,
    critical: false,
    description: 'Annual energy production (kWh) calculation from performance matrix using reference climate datasets (IEC 61853-3).',
    documentFormatNumber: 'SLX-FMT-61853-P3-001',
    revision: '01',
    equipment: ['Software (energy rating model)', 'Performance matrix from P1 & P2'],
    testConditions: [
      { label: 'Climate dataset', value: 'IEC 61853-4 (Low/Mid/High latitude)', unit: '-', source: 'IEC 61853-4:2018' },
    ],
    acceptanceCriteria: [
      { id: 'ac-853p3-1', parameter: 'Energy rating consistency', operator: 'manual', limit: 'Within ±2% of model prediction', unit: '%', critical: false, description: 'Calculated energy rating consistent with model' },
    ],
    measurements: [
      { id: 'm-853p3-1', label: 'Energy rating (Low-latitude climate)', unit: 'kWh/kWp·yr', type: 'number', required: false },
      { id: 'm-853p3-2', label: 'Energy rating (Mid-latitude climate)', unit: 'kWh/kWp·yr', type: 'number', required: true },
      { id: 'm-853p3-3', label: 'Energy rating (High-latitude climate)', unit: 'kWh/kWp·yr', type: 'number', required: false },
    ],
    hasIVCurve: false,
  },
]
