import type { ProtocolDefinition } from '@/lib/protocol-types'

export const IEC61215_PROTOCOLS: ProtocolDefinition[] = [
  {
    id: 'mqt10.1',
    code: 'MQT 10.1',
    name: 'Visual Inspection',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.1',
    category: 'visual',
    duration: '1h',
    sequence: 1,
    critical: false,
    description: 'Examination of the module for construction defects, workmanship issues, and appearance anomalies per IEC 61215-2 cl 4.1.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.1-001',
    revision: '01',
    equipment: ['Lightbox (min 1000 lux)', 'Magnifier 10×', 'Calibrated camera', 'Ruler/calipers'],
    testConditions: [
      { label: 'Illumination', value: '≥ 1000', unit: 'lux', source: 'IEC 61215-2:2021 cl 4.1' },
      { label: 'Viewing angle', value: '45° to 90°', unit: 'deg', source: 'IEC 61215-2:2021 cl 4.1' },
    ],
    acceptanceCriteria: [
      { id: 'ac-vi-1', parameter: 'Broken/cracked cells', operator: 'manual', limit: 'None', limitValue: 0, unit: 'count', critical: true, description: 'No broken, cracked, or chipped cells visible' },
      { id: 'ac-vi-2', parameter: 'Delamination', operator: 'manual', limit: 'None', limitValue: 0, unit: '-', critical: true, description: 'No delamination or blistering in the active area' },
      { id: 'ac-vi-3', parameter: 'Interconnect damage', operator: 'manual', limit: 'None', limitValue: 0, unit: '-', critical: true, description: 'No broken or severely corroded interconnects' },
      { id: 'ac-vi-4', parameter: 'Labels readability', operator: 'manual', limit: 'Readable', unit: '-', critical: false, description: 'All labels legible and firmly attached' },
      { id: 'ac-vi-5', parameter: 'Frame/JB/Connector condition', operator: 'manual', limit: 'No damage', unit: '-', critical: false, description: 'Frame not bent; JB lid closes; connectors undamaged' },
    ],
    measurements: [
      { id: 'm-vi-1', label: 'Broken cells', unit: 'count', type: 'number', required: true, min: 0, criterionId: 'ac-vi-1', placeholder: '0' },
      { id: 'm-vi-2', label: 'Delamination present', unit: '-', type: 'boolean', required: true, criterionId: 'ac-vi-2' },
      { id: 'm-vi-3', label: 'Interconnect damage', unit: '-', type: 'boolean', required: true, criterionId: 'ac-vi-3' },
      { id: 'm-vi-4', label: 'Labels readable', unit: '-', type: 'boolean', required: true, criterionId: 'ac-vi-4' },
      { id: 'm-vi-5', label: 'Frame/JB/Connector condition', unit: '-', type: 'select', options: ['Good', 'Minor damage (acceptable)', 'Major damage (fail)'], required: true },
      { id: 'm-vi-6', label: 'Discoloration present', unit: '-', type: 'boolean', required: false },
      { id: 'm-vi-7', label: 'Bubbles/voids in encapsulant', unit: '-', type: 'boolean', required: false },
      { id: 'm-vi-8', label: 'Observations', unit: '-', type: 'textarea', required: false, placeholder: 'Describe any anomalies observed...' },
    ],
    hasIVCurve: false,
    notes: 'Perform before and after each stress test sequence. Record photographic evidence for all defects.',
  },

  {
    id: 'mqt10.2',
    code: 'MQT 10.2',
    name: 'Maximum Power Determination (STC)',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.2',
    category: 'electrical',
    duration: '2h',
    sequence: 2,
    critical: true,
    description: 'I-V characteristic measurement at STC (1000 W/m², 25 °C, AM1.5G) per IEC 61215-2 cl 4.2 and IEC 60904-1.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.2-001',
    revision: '01',
    equipment: ['Solar Flash Tester (class AAA)', 'Reference Cell (calibrated)', 'Pt100 temperature sensor', 'IV tracer'],
    testConditions: [
      { label: 'Irradiance', value: '1000', unit: 'W/m²', source: 'IEC 60904-1:2020' },
      { label: 'Cell temperature', value: '25 ± 2', unit: '°C', source: 'IEC 60904-1:2020' },
      { label: 'Spectrum', value: 'AM1.5G (IEC 60904-3)', unit: '-', source: 'IEC 60904-3:2019' },
    ],
    acceptanceCriteria: [
      { id: 'ac-stc-1', parameter: 'Pmax', operator: 'gte', limit: 'Pnom × 0.97', limitValue: -3, unit: '%', critical: true, description: 'Measured Pmax ≥ 97% of rated Pnom' },
      { id: 'ac-stc-2', parameter: 'Voc deviation', operator: 'between', limit: '±3% of datasheet', unit: '%', critical: false, description: 'Voc within ±3% of rated value' },
      { id: 'ac-stc-3', parameter: 'Isc deviation', operator: 'between', limit: '±3% of datasheet', unit: '%', critical: false, description: 'Isc within ±3% of rated value' },
      { id: 'ac-stc-4', parameter: 'FF deviation', operator: 'between', limit: '±3% of datasheet', unit: '%', critical: false, description: 'Fill Factor within ±3% of rated value' },
    ],
    measurements: [
      { id: 'm-stc-1', label: 'Pmax (measured)', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax', min: 0, criterionId: 'ac-stc-1' },
      { id: 'm-stc-2', label: 'Pnom (rated)', unit: 'W', type: 'number', required: true, min: 0, placeholder: 'From module datasheet' },
      { id: 'm-stc-3', label: 'Voc (measured)', unit: 'V', type: 'number', required: true, autoFillFrom: 'voc', min: 0 },
      { id: 'm-stc-4', label: 'Voc (rated)', unit: 'V', type: 'number', required: true, placeholder: 'From datasheet' },
      { id: 'm-stc-5', label: 'Isc (measured)', unit: 'A', type: 'number', required: true, autoFillFrom: 'isc', min: 0 },
      { id: 'm-stc-6', label: 'Isc (rated)', unit: 'A', type: 'number', required: true, placeholder: 'From datasheet' },
      { id: 'm-stc-7', label: 'Vmp (measured)', unit: 'V', type: 'number', required: false, autoFillFrom: 'vmp', min: 0 },
      { id: 'm-stc-8', label: 'Imp (measured)', unit: 'A', type: 'number', required: false, autoFillFrom: 'imp', min: 0 },
      { id: 'm-stc-9', label: 'Fill Factor (FF)', unit: '%', type: 'number', required: false, autoFillFrom: 'ff', min: 0, max: 100 },
      { id: 'm-stc-10', label: 'Efficiency (η)', unit: '%', type: 'number', required: false, autoFillFrom: 'efficiency', min: 0 },
      { id: 'm-stc-11', label: 'Cell temperature at test', unit: '°C', type: 'number', required: true, autoFillFrom: 'cellTemp' },
      { id: 'm-stc-12', label: 'Irradiance at test', unit: 'W/m²', type: 'number', required: true, autoFillFrom: 'irradiance' },
    ],
    rawDataConfig: {
      type: 'flasher_iv',
      description: 'Flash tester CSV export (IV curve + parameters)',
      acceptedFormats: ['.csv', '.xlsx', '.xls', '.txt'],
      expectedHeaders: ['V', 'I', 'Voltage', 'Current', 'Voc', 'Isc', 'Pmax', 'Vmp', 'Imp'],
      columnMapping: {
        voltage: ['V', 'Voltage', 'VOLTAGE', 'v', 'U', 'Udc'],
        current: ['I', 'Current', 'CURRENT', 'i', 'Idc'],
        voc: ['Voc', 'VOC', 'V_OC', 'Uoc'],
        isc: ['Isc', 'ISC', 'I_SC'],
        pmax: ['Pmax', 'PMAX', 'P_max', 'Pmpp', 'Pmp'],
        vmp: ['Vmp', 'VMP', 'Vmpp', 'V_mp'],
        imp: ['Imp', 'IMP', 'Impp', 'I_mp'],
        ff: ['FF', 'FillFactor', 'Fill Factor'],
        efficiency: ['Eff', 'Efficiency', 'eta', 'η', 'Eff%'],
        irradiance: ['Irr', 'Irradiance', 'G', 'E'],
        cellTemp: ['Tc', 'Tcell', 'T_cell', 'CellTemp', 'ModuleTemp'],
      },
    },
    hasIVCurve: true,
  },

  {
    id: 'mqt10.3',
    code: 'MQT 10.3',
    name: 'Insulation Test',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.3',
    category: 'safety',
    duration: '1h',
    sequence: 3,
    critical: true,
    description: 'Evaluation of insulation resistance between active circuits and module frame per IEC 61215-2 cl 4.3.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.3-001',
    revision: '01',
    equipment: ['Insulation resistance tester (1000V DC)', 'Test probes', 'Safety gloves'],
    testConditions: [
      { label: 'Test voltage (Vsys < 50V)', value: '500', unit: 'VDC', source: 'IEC 61215-2:2021 cl 4.3' },
      { label: 'Test voltage (Vsys ≥ 50V)', value: '1000', unit: 'VDC', source: 'IEC 61215-2:2021 cl 4.3' },
      { label: 'Test duration', value: '60', unit: 's', source: 'IEC 61215-2:2021 cl 4.3' },
    ],
    acceptanceCriteria: [
      { id: 'ac-ins-1', parameter: 'R_ins × Module Area', operator: 'gte', limit: '40 MΩ·m²', limitValue: 40, unit: 'MΩ·m²', critical: true, description: 'Insulation resistance × module area ≥ 40 MΩ·m²' },
      { id: 'ac-ins-2', parameter: 'Dielectric breakdown', operator: 'manual', limit: 'No breakdown', unit: '-', critical: true, description: 'No dielectric breakdown during test' },
    ],
    measurements: [
      { id: 'm-ins-1', label: 'Insulation resistance (R_ins)', unit: 'MΩ', type: 'number', required: true, min: 0, criterionId: 'ac-ins-1' },
      { id: 'm-ins-2', label: 'Module area (L × W)', unit: 'm²', type: 'number', required: true, min: 0 },
      { id: 'm-ins-3', label: 'R_ins × Area product', unit: 'MΩ·m²', type: 'number', required: true, min: 0 },
      { id: 'm-ins-4', label: 'Test voltage applied', unit: 'VDC', type: 'number', required: true },
      { id: 'm-ins-5', label: 'Dielectric breakdown occurred', unit: '-', type: 'boolean', required: true, criterionId: 'ac-ins-2' },
      { id: 'm-ins-6', label: 'Test duration', unit: 's', type: 'number', required: true },
    ],
    rawDataConfig: {
      type: 'insulation_log',
      description: 'Insulation tester data log (CSV/TXT)',
      acceptedFormats: ['.csv', '.txt', '.xlsx'],
      columnMapping: {
        resistance: ['R', 'Resistance', 'Rins', 'MΩ', 'Mohm'],
        voltage: ['V', 'Voltage', 'TestVoltage'],
        timestamp: ['Time', 'Timestamp', 'DateTime'],
      },
    },
    hasIVCurve: false,
  },

  {
    id: 'mqt10.4',
    code: 'MQT 10.4',
    name: 'Temperature Coefficients Measurement',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.4',
    category: 'electrical',
    duration: '4h',
    sequence: 4,
    critical: false,
    description: 'Determination of temperature coefficients α(Isc), β(Voc), γ(Pmax) per IEC 60891 method.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.4-001',
    revision: '01',
    equipment: ['Flash tester or solar simulator', 'Thermal chamber', 'Pt100 sensors (min 4)', 'Reference cell'],
    testConditions: [
      { label: 'Temperature range', value: '15 to 75', unit: '°C', source: 'IEC 61215-2:2021 cl 4.4' },
      { label: 'Temperature points', value: '≥ 5', unit: '-', source: 'IEC 61215-2:2021 cl 4.4' },
      { label: 'Irradiance', value: '1000', unit: 'W/m²', source: 'IEC 60891:2021' },
    ],
    acceptanceCriteria: [
      { id: 'ac-tc-1', parameter: 'α(Isc) vs datasheet', operator: 'between', limit: '±20% of datasheet', unit: '%/°C', critical: false, description: 'Measured α within ±20% of rated value' },
      { id: 'ac-tc-2', parameter: 'β(Voc) vs datasheet', operator: 'between', limit: '±20% of datasheet', unit: '%/°C', critical: false, description: 'Measured β within ±20% of rated value' },
      { id: 'ac-tc-3', parameter: 'γ(Pmax) vs datasheet', operator: 'between', limit: '±20% of datasheet', unit: '%/°C', critical: false, description: 'Measured γ within ±20% of rated value' },
    ],
    measurements: [
      { id: 'm-tc-1', label: 'α (Isc temp coefficient)', unit: '%/°C', type: 'number', required: true },
      { id: 'm-tc-2', label: 'α (rated, datasheet)', unit: '%/°C', type: 'number', required: true },
      { id: 'm-tc-3', label: 'β (Voc temp coefficient)', unit: '%/°C', type: 'number', required: true },
      { id: 'm-tc-4', label: 'β (rated, datasheet)', unit: '%/°C', type: 'number', required: true },
      { id: 'm-tc-5', label: 'γ (Pmax temp coefficient)', unit: '%/°C', type: 'number', required: true },
      { id: 'm-tc-6', label: 'γ (rated, datasheet)', unit: '%/°C', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.5',
    code: 'MQT 10.5',
    name: 'NMOT Determination',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.5',
    category: 'electrical',
    duration: '8h',
    sequence: 5,
    critical: false,
    description: 'Nominal Module Operating Temperature (NMOT) measurement at reference conditions (800 W/m², 20°C, 1 m/s wind).',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.5-001',
    revision: '01',
    equipment: ['Pyranometer', 'Anemometer', 'Thermocouples (min 4, rear surface)', 'Ambient temp sensor'],
    testConditions: [
      { label: 'Reference irradiance', value: '800', unit: 'W/m²', source: 'IEC 61215-2:2021 cl 4.5' },
      { label: 'Reference ambient temp', value: '20', unit: '°C', source: 'IEC 61215-2:2021 cl 4.5' },
      { label: 'Reference wind speed', value: '1', unit: 'm/s', source: 'IEC 61215-2:2021 cl 4.5' },
    ],
    acceptanceCriteria: [
      { id: 'ac-nmot-1', parameter: 'NMOT vs declared', operator: 'between', limit: '±2°C of declared NMOT', limitValue: 2, unit: '°C', critical: false, description: 'Measured NMOT within ±2°C of manufacturer declared value' },
    ],
    measurements: [
      { id: 'm-nmot-1', label: 'NMOT (measured)', unit: '°C', type: 'number', required: true },
      { id: 'm-nmot-2', label: 'NMOT (declared)', unit: '°C', type: 'number', required: true, placeholder: 'From module datasheet' },
      { id: 'm-nmot-3', label: 'Ambient temp at test', unit: '°C', type: 'number', required: true },
      { id: 'm-nmot-4', label: 'Irradiance at test', unit: 'W/m²', type: 'number', required: true },
      { id: 'm-nmot-5', label: 'Wind speed at test', unit: 'm/s', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.6',
    code: 'MQT 10.6',
    name: 'Performance at STC and NMOT',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.6',
    category: 'electrical',
    duration: '3h',
    sequence: 6,
    critical: false,
    description: 'IV measurement at STC and NMOT conditions to verify module performance per IEC 61215-2 cl 4.6.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.6-001',
    revision: '01',
    equipment: ['Flash tester', 'Reference cell', 'Temperature sensor'],
    testConditions: [
      { label: 'STC irradiance', value: '1000', unit: 'W/m²', source: 'IEC 60904-1' },
      { label: 'STC temperature', value: '25 ± 2', unit: '°C', source: 'IEC 60904-1' },
      { label: 'NMOT irradiance', value: '800', unit: 'W/m²', source: 'IEC 61215-2:2021 cl 4.6' },
    ],
    acceptanceCriteria: [
      { id: 'ac-perf-1', parameter: 'Pmax at STC', operator: 'gte', limit: 'Pnom × 0.97', unit: 'W', critical: true, description: 'Power at STC ≥ 97% of rated' },
      { id: 'ac-perf-2', parameter: 'Pmax at NMOT', operator: 'gte', limit: 'Expected from temp coefficients', unit: 'W', critical: false, description: 'Power at NMOT consistent with temperature correction' },
    ],
    measurements: [
      { id: 'm-perf-1', label: 'Pmax at STC', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-perf-2', label: 'Pmax at NMOT', unit: 'W', type: 'number', required: true },
      { id: 'm-perf-3', label: 'Voc at STC', unit: 'V', type: 'number', required: true, autoFillFrom: 'voc' },
      { id: 'm-perf-4', label: 'Isc at STC', unit: 'A', type: 'number', required: true, autoFillFrom: 'isc' },
    ],
    rawDataConfig: {
      type: 'flasher_iv',
      description: 'Flash tester CSV (IV curve)',
      acceptedFormats: ['.csv', '.xlsx'],
      columnMapping: {
        voltage: ['V', 'Voltage', 'VOLTAGE'],
        current: ['I', 'Current', 'CURRENT'],
        voc: ['Voc', 'VOC'], isc: ['Isc', 'ISC'],
        pmax: ['Pmax', 'PMAX'], vmp: ['Vmp', 'VMP'], imp: ['Imp', 'IMP'],
      },
    },
    hasIVCurve: true,
  },

  {
    id: 'mqt10.7',
    code: 'MQT 10.7',
    name: 'Performance at Low Irradiance',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.7',
    category: 'electrical',
    duration: '2h',
    sequence: 7,
    critical: false,
    description: 'I-V measurement at 200 W/m², 25°C to evaluate low-light performance relative to STC.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.7-001',
    revision: '01',
    equipment: ['Flash tester with ND filters', 'Reference cell', 'Temperature sensor'],
    testConditions: [
      { label: 'Test irradiance', value: '200', unit: 'W/m²', source: 'IEC 61215-2:2021 cl 4.7' },
      { label: 'Cell temperature', value: '25 ± 2', unit: '°C', source: 'IEC 61215-2:2021 cl 4.7' },
    ],
    acceptanceCriteria: [
      { id: 'ac-li-1', parameter: 'η(200)/η(1000)', operator: 'gte', limit: '0.95', limitValue: 0.95, unit: '-', critical: false, description: 'Low irradiance efficiency ratio ≥ 0.95' },
    ],
    measurements: [
      { id: 'm-li-1', label: 'Pmax at 200 W/m²', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-li-2', label: 'Efficiency at 200 W/m²', unit: '%', type: 'number', required: true },
      { id: 'm-li-3', label: 'Efficiency at 1000 W/m² (from MQT 10.2)', unit: '%', type: 'number', required: true },
      { id: 'm-li-4', label: 'η ratio (200/1000)', unit: '-', type: 'number', required: true, criterionId: 'ac-li-1' },
    ],
    rawDataConfig: {
      type: 'flasher_iv',
      description: 'Flash tester CSV at 200 W/m²',
      acceptedFormats: ['.csv', '.xlsx'],
      columnMapping: { voltage: ['V', 'Voltage'], current: ['I', 'Current'], pmax: ['Pmax'], voc: ['Voc'], isc: ['Isc'] },
    },
    hasIVCurve: true,
  },

  {
    id: 'mqt10.8',
    code: 'MQT 10.8',
    name: 'Outdoor Exposure',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.8',
    category: 'environmental',
    duration: '60h',
    sequence: 8,
    critical: false,
    description: 'Outdoor exposure to natural weathering conditions to detect UV-sensitive degradation not caught in accelerated tests.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.8-001',
    revision: '01',
    equipment: ['Outdoor test rack (tilt = local latitude)', 'Pyranometer', 'Data logger'],
    testConditions: [
      { label: 'Total exposure', value: '60', unit: 'kWh/m²', source: 'IEC 61215-2:2021 cl 4.8' },
      { label: 'Module tilt', value: 'Local latitude', unit: 'deg', source: 'IEC 61215-2:2021 cl 4.8' },
    ],
    acceptanceCriteria: [
      { id: 'ac-oe-1', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: true, description: 'Power loss ≤ 5% after outdoor exposure' },
      { id: 'ac-oe-2', parameter: 'Visual defects', operator: 'manual', limit: 'None new', unit: '-', critical: false, description: 'No new visual defects per MQT 10.1' },
    ],
    measurements: [
      { id: 'm-oe-1', label: 'Pmax before exposure', unit: 'W', type: 'number', required: true },
      { id: 'm-oe-2', label: 'Pmax after exposure', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-oe-3', label: 'Pmax degradation', unit: '%', type: 'number', required: true, criterionId: 'ac-oe-1' },
      { id: 'm-oe-4', label: 'Total exposure achieved', unit: 'kWh/m²', type: 'number', required: true },
      { id: 'm-oe-5', label: 'New visual defects', unit: '-', type: 'boolean', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.9',
    code: 'MQT 10.9',
    name: 'Hot Spot Endurance Test',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.9',
    category: 'environmental',
    duration: '5h',
    sequence: 9,
    critical: false,
    description: 'Test for hot spot resistance: one cell shaded and bypass diode tested under irradiance for 5 hours.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.9-001',
    revision: '01',
    equipment: ['Solar simulator or outdoor', 'IR camera', 'Black tape/shade card', 'Pyranometer'],
    testConditions: [
      { label: 'Irradiance', value: '1000', unit: 'W/m²', source: 'IEC 61215-2:2021 cl 4.9' },
      { label: 'Exposure duration', value: '5 × 1', unit: 'h per worst case', source: 'IEC 61215-2:2021 cl 4.9' },
    ],
    acceptanceCriteria: [
      { id: 'ac-hs-1', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: true, description: 'Power loss ≤ 5% after hot spot test' },
      { id: 'ac-hs-2', parameter: 'Hot spot temperature (worst-case cell)', operator: 'manual', limit: 'No combustion/melting', unit: '°C', critical: true, description: 'No fire, melting or severe damage' },
    ],
    measurements: [
      { id: 'm-hs-1', label: 'Pmax before test', unit: 'W', type: 'number', required: true },
      { id: 'm-hs-2', label: 'Pmax after test', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-hs-3', label: 'Pmax degradation', unit: '%', type: 'number', required: true, criterionId: 'ac-hs-1' },
      { id: 'm-hs-4', label: 'Max hot spot temperature', unit: '°C', type: 'number', required: true },
      { id: 'm-hs-5', label: 'Shaded cell fraction', unit: '-', type: 'select', options: ['Full cell', '1/3 cell', '2/3 cell', '1/4 cell'], required: true },
    ],
    hasIVCurve: false,
    notes: 'Determine worst-case shading configuration from initial I-V measurements before stress.',
  },

  {
    id: 'mqt10.10',
    code: 'MQT 10.10',
    name: 'UV Preconditioning',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.10',
    category: 'environmental',
    duration: '120h',
    sequence: 10,
    critical: false,
    description: 'UV exposure to identify UV-related degradation modes prior to thermal cycling and humidity-freeze sequences.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.10-001',
    revision: '01',
    equipment: ['UV chamber (280–400 nm)', 'UV radiometer', 'Module temperature sensor'],
    testConditions: [
      { label: 'Total UV dose (280–400 nm)', value: '15', unit: 'kWh/m²', source: 'IEC 61215-2:2021 cl 4.10' },
      { label: 'UVB dose (280–320 nm)', value: '5', unit: 'kWh/m²', source: 'IEC 61215-2:2021 cl 4.10' },
      { label: 'Module temperature', value: '60 ± 5', unit: '°C', source: 'IEC 61215-2:2021 cl 4.10' },
    ],
    acceptanceCriteria: [
      { id: 'ac-uv-1', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: true, description: 'Power loss ≤ 5% after UV preconditioning' },
      { id: 'ac-uv-2', parameter: 'Visual defects', operator: 'manual', limit: 'None new', unit: '-', critical: false, description: 'No new visible defects' },
    ],
    measurements: [
      { id: 'm-uv-1', label: 'Pmax before UV', unit: 'W', type: 'number', required: true },
      { id: 'm-uv-2', label: 'Pmax after UV', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-uv-3', label: 'Pmax degradation', unit: '%', type: 'number', required: true, criterionId: 'ac-uv-1' },
      { id: 'm-uv-4', label: 'Total UV dose achieved', unit: 'kWh/m²', type: 'number', required: true },
      { id: 'm-uv-5', label: 'UVB dose achieved', unit: 'kWh/m²', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.11',
    code: 'MQT 10.11',
    name: 'Thermal Cycling (TC200/TC400)',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.11',
    category: 'environmental',
    duration: '800h',
    sequence: 11,
    critical: true,
    description: 'Thermal cycling test (200 or 400 cycles, -40°C to +85°C) to detect mechanical degradation from differential thermal expansion.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.11-001',
    revision: '01',
    equipment: ['Thermal cycling chamber', 'Module temperature sensors (min 4)', 'Current injection source'],
    testConditions: [
      { label: 'Temperature range', value: '-40 to +85', unit: '°C', source: 'IEC 61215-2:2021 cl 4.11' },
      { label: 'Ramp rate', value: '≤ 100', unit: '°C/min', source: 'IEC 61215-2:2021 cl 4.11' },
      { label: 'Dwell time at extremes', value: '≥ 10', unit: 'min', source: 'IEC 61215-2:2021 cl 4.11' },
      { label: 'Number of cycles (TC200)', value: '200', unit: 'cycles', source: 'IEC 61215-2:2021 cl 4.11' },
      { label: 'Current injection', value: 'Isc', unit: 'A', source: 'IEC 61215-2:2021 cl 4.11' },
    ],
    acceptanceCriteria: [
      { id: 'ac-tcy-1', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: true, description: 'Power loss ≤ 5% after thermal cycling' },
      { id: 'ac-tcy-2', parameter: 'Insulation (R_ins × Area)', operator: 'gte', limit: '40 MΩ·m²', limitValue: 40, unit: 'MΩ·m²', critical: true, description: 'Insulation resistance maintained after cycling' },
      { id: 'ac-tcy-3', parameter: 'Visual defects', operator: 'manual', limit: 'None new', unit: '-', critical: false, description: 'No new visible defects per MQT 10.1' },
    ],
    measurements: [
      { id: 'm-tcy-1', label: 'Pmax before cycling', unit: 'W', type: 'number', required: true },
      { id: 'm-tcy-2', label: 'Pmax after cycling', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-tcy-3', label: 'Pmax degradation', unit: '%', type: 'number', required: true, criterionId: 'ac-tcy-1' },
      { id: 'm-tcy-4', label: 'Cycles completed', unit: 'cycles', type: 'number', required: true },
      { id: 'm-tcy-5', label: 'R_ins × Area (after)', unit: 'MΩ·m²', type: 'number', required: true, criterionId: 'ac-tcy-2' },
      { id: 'm-tcy-6', label: 'New visual defects', unit: '-', type: 'boolean', required: true },
    ],
    rawDataConfig: {
      type: 'chamber_log',
      description: 'Chamber temperature profile log',
      acceptedFormats: ['.csv', '.xlsx'],
      columnMapping: { time: ['Time', 'DateTime'], temperature: ['Temp', 'Temperature', 'T_chamber'] },
    },
    hasIVCurve: false,
  },

  {
    id: 'mqt10.12',
    code: 'MQT 10.12',
    name: 'Humidity-Freeze (HF10)',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.12',
    category: 'environmental',
    duration: '300h',
    sequence: 12,
    critical: true,
    description: '10 humidity-freeze cycles (85°C/85%RH → -40°C) to test resistance to moisture ingress at temperature extremes.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.12-001',
    revision: '01',
    equipment: ['Combined humidity-freeze chamber', 'Temperature/humidity sensors', 'Insulation tester'],
    testConditions: [
      { label: 'High phase temp', value: '85 ± 2', unit: '°C', source: 'IEC 61215-2:2021 cl 4.12' },
      { label: 'High phase humidity', value: '85 ± 5', unit: '%RH', source: 'IEC 61215-2:2021 cl 4.12' },
      { label: 'Low phase temp', value: '-40 ± 2', unit: '°C', source: 'IEC 61215-2:2021 cl 4.12' },
      { label: 'Number of cycles', value: '10', unit: 'cycles', source: 'IEC 61215-2:2021 cl 4.12' },
    ],
    acceptanceCriteria: [
      { id: 'ac-hf-1', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: true, description: 'Power loss ≤ 5% after humidity-freeze' },
      { id: 'ac-hf-2', parameter: 'R_ins × Area', operator: 'gte', limit: '40 MΩ·m²', limitValue: 40, unit: 'MΩ·m²', critical: true, description: 'Insulation maintained' },
    ],
    measurements: [
      { id: 'm-hf-1', label: 'Pmax before HF', unit: 'W', type: 'number', required: true },
      { id: 'm-hf-2', label: 'Pmax after HF', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-hf-3', label: 'Pmax degradation', unit: '%', type: 'number', required: true, criterionId: 'ac-hf-1' },
      { id: 'm-hf-4', label: 'Cycles completed', unit: 'cycles', type: 'number', required: true },
      { id: 'm-hf-5', label: 'R_ins × Area (after)', unit: 'MΩ·m²', type: 'number', required: true, criterionId: 'ac-hf-2' },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.13',
    code: 'MQT 10.13',
    name: 'Damp Heat (DH1000)',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.13',
    category: 'environmental',
    duration: '1050h',
    sequence: 13,
    critical: true,
    description: '1000 h at 85°C/85%RH to test resistance to long-term humidity exposure and delamination.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.13-001',
    revision: '01',
    equipment: ['Damp heat chamber (85°C/85%RH capability)', 'Temperature/humidity sensors', 'Flash tester', 'Insulation tester'],
    testConditions: [
      { label: 'Temperature', value: '85 ± 2', unit: '°C', source: 'IEC 61215-2:2021 cl 4.13' },
      { label: 'Relative humidity', value: '85 ± 5', unit: '%RH', source: 'IEC 61215-2:2021 cl 4.13' },
      { label: 'Duration', value: '1000', unit: 'h', source: 'IEC 61215-2:2021 cl 4.13' },
    ],
    acceptanceCriteria: [
      { id: 'ac-dh-1', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: true, description: 'Power loss ≤ 5% after damp heat' },
      { id: 'ac-dh-2', parameter: 'R_ins × Area', operator: 'gte', limit: '40 MΩ·m²', limitValue: 40, unit: 'MΩ·m²', critical: true, description: 'Insulation maintained after damp heat' },
    ],
    measurements: [
      { id: 'm-dh-1', label: 'Pmax before DH', unit: 'W', type: 'number', required: true },
      { id: 'm-dh-2', label: 'Pmax after DH', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-dh-3', label: 'Pmax degradation', unit: '%', type: 'number', required: true, criterionId: 'ac-dh-1' },
      { id: 'm-dh-4', label: 'Duration achieved', unit: 'h', type: 'number', required: true },
      { id: 'm-dh-5', label: 'R_ins × Area (after)', unit: 'MΩ·m²', type: 'number', required: true, criterionId: 'ac-dh-2' },
    ],
    rawDataConfig: {
      type: 'chamber_log',
      description: 'Chamber log (temp/humidity over time)',
      acceptedFormats: ['.csv', '.xlsx'],
      columnMapping: { time: ['Time', 'DateTime'], temperature: ['Temp', 'Temperature'], humidity: ['RH', 'Humidity', '%RH'] },
    },
    hasIVCurve: false,
  },

  {
    id: 'mqt10.14',
    code: 'MQT 10.14',
    name: 'Robustness of Terminations',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.14',
    category: 'mechanical',
    duration: '2h',
    sequence: 14,
    critical: false,
    description: 'Pull and torque test on cable terminations and connectors to verify mechanical robustness.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.14-001',
    revision: '01',
    equipment: ['Tensile tester / force gauge', 'Torque wrench', 'Connector holding fixture'],
    testConditions: [
      { label: 'Pull force (cable lug)', value: '≥ 100', unit: 'N', source: 'IEC 61215-2:2021 cl 4.14' },
      { label: 'Torque test', value: '≥ 1.0', unit: 'N·m', source: 'IEC 61215-2:2021 cl 4.14' },
    ],
    acceptanceCriteria: [
      { id: 'ac-rt-1', parameter: 'Pull force', operator: 'gte', limit: '100 N', limitValue: 100, unit: 'N', critical: false, description: 'Cable lug withstands ≥ 100 N pull' },
      { id: 'ac-rt-2', parameter: 'No damage after test', operator: 'manual', limit: 'No breakage/loosening', unit: '-', critical: true, description: 'No breakage, loosening or damage to terminations' },
    ],
    measurements: [
      { id: 'm-rt-1', label: 'Pull force (positive terminal)', unit: 'N', type: 'number', required: true, criterionId: 'ac-rt-1' },
      { id: 'm-rt-2', label: 'Pull force (negative terminal)', unit: 'N', type: 'number', required: true },
      { id: 'm-rt-3', label: 'Damage observed after pull test', unit: '-', type: 'boolean', required: true },
      { id: 'm-rt-4', label: 'Torque applied', unit: 'N·m', type: 'number', required: false },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.15',
    code: 'MQT 10.15',
    name: 'Wet Leakage Current Test',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.15',
    category: 'safety',
    duration: '2h',
    sequence: 15,
    critical: true,
    description: 'Wet insulation test simulating rain conditions to check electrical isolation after surface wetting.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.15-001',
    revision: '01',
    equipment: ['Insulation tester', 'Surfactant solution (ASTM D1183)', 'Test probes', 'Safety equipment'],
    testConditions: [
      { label: 'Surfactant solution resistivity', value: '3500 ± 350', unit: 'Ω·cm', source: 'IEC 61215-2:2021 cl 4.15' },
      { label: 'Test voltage', value: '500 or 1000', unit: 'VDC', source: 'IEC 61215-2:2021 cl 4.15' },
    ],
    acceptanceCriteria: [
      { id: 'ac-wl-1', parameter: 'R_ins × Area (wet)', operator: 'gte', limit: '40 MΩ·m²', limitValue: 40, unit: 'MΩ·m²', critical: true, description: 'Wet insulation resistance × area ≥ 40 MΩ·m²' },
    ],
    measurements: [
      { id: 'm-wl-1', label: 'Insulation resistance (wet)', unit: 'MΩ', type: 'number', required: true },
      { id: 'm-wl-2', label: 'Module area', unit: 'm²', type: 'number', required: true },
      { id: 'm-wl-3', label: 'R_ins × Area (wet)', unit: 'MΩ·m²', type: 'number', required: true, criterionId: 'ac-wl-1' },
      { id: 'm-wl-4', label: 'Solution resistivity', unit: 'Ω·cm', type: 'number', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.16',
    code: 'MQT 10.16',
    name: 'Mechanical Load Test',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.16',
    category: 'mechanical',
    duration: '12h',
    sequence: 16,
    critical: false,
    description: 'Static mechanical load (front and rear) to simulate wind and snow loads per IEC 61215-2 cl 4.16.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.16-001',
    revision: '01',
    equipment: ['Mechanical load test fixture', 'Pressure bag or uniform load plates', 'Load measurement system'],
    testConditions: [
      { label: 'Front (wind/snow) pressure', value: '2400', unit: 'Pa', source: 'IEC 61215-2:2021 cl 4.16' },
      { label: 'Rear (uplift) pressure', value: '2400', unit: 'Pa', source: 'IEC 61215-2:2021 cl 4.16' },
      { label: 'Load cycles per direction', value: '3', unit: 'cycles', source: 'IEC 61215-2:2021 cl 4.16' },
      { label: 'Hold duration per cycle', value: '1', unit: 'h', source: 'IEC 61215-2:2021 cl 4.16' },
    ],
    acceptanceCriteria: [
      { id: 'ac-ml-1', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: true, description: 'Power loss ≤ 5% after mechanical load' },
      { id: 'ac-ml-2', parameter: 'Cell/glass cracks', operator: 'manual', limit: 'None', unit: '-', critical: true, description: 'No cracks in cells or glass' },
      { id: 'ac-ml-3', parameter: 'Electrical continuity', operator: 'manual', limit: 'Maintained', unit: '-', critical: true, description: 'Electrical continuity maintained throughout' },
    ],
    measurements: [
      { id: 'm-ml-1', label: 'Pmax before load test', unit: 'W', type: 'number', required: true },
      { id: 'm-ml-2', label: 'Pmax after load test', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-ml-3', label: 'Pmax degradation', unit: '%', type: 'number', required: true, criterionId: 'ac-ml-1' },
      { id: 'm-ml-4', label: 'Front load applied', unit: 'Pa', type: 'number', required: true },
      { id: 'm-ml-5', label: 'Rear load applied', unit: 'Pa', type: 'number', required: true },
      { id: 'm-ml-6', label: 'Cell/glass cracks observed', unit: '-', type: 'boolean', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.17',
    code: 'MQT 10.17',
    name: 'Hail Test',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.17',
    category: 'mechanical',
    duration: '2h',
    sequence: 17,
    critical: false,
    description: 'Hail impact test using 25 mm ice balls at 23 m/s on 11 critical impact points.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.17-001',
    revision: '01',
    equipment: ['Hail launcher / gun', 'Ice ball mold (25 mm dia)', 'High-speed camera', 'Chronograph'],
    testConditions: [
      { label: 'Ice ball diameter', value: '25', unit: 'mm', source: 'IEC 61215-2:2021 cl 4.17' },
      { label: 'Impact velocity', value: '23 ± 1', unit: 'm/s', source: 'IEC 61215-2:2021 cl 4.17' },
      { label: 'Impact points', value: '11', unit: 'points', source: 'IEC 61215-2:2021 cl 4.17' },
      { label: 'Impact angle', value: '90° (normal)', unit: 'deg', source: 'IEC 61215-2:2021 cl 4.17' },
    ],
    acceptanceCriteria: [
      { id: 'ac-hail-1', parameter: 'Glass breakage', operator: 'manual', limit: 'None', unit: '-', critical: true, description: 'No glass breakage or cracking' },
      { id: 'ac-hail-2', parameter: 'Cell damage', operator: 'manual', limit: 'None', unit: '-', critical: true, description: 'No cracked or broken cells (confirmed by EL/visual)' },
      { id: 'ac-hail-3', parameter: 'Pmax degradation', operator: 'max_degradation', limit: '5%', limitValue: 5, unit: '%', critical: false, description: 'Power loss ≤ 5%' },
    ],
    measurements: [
      { id: 'm-hail-1', label: 'Measured impact velocity', unit: 'm/s', type: 'number', required: true },
      { id: 'm-hail-2', label: 'Ice ball diameter verified', unit: 'mm', type: 'number', required: true },
      { id: 'm-hail-3', label: 'Glass breakage', unit: '-', type: 'boolean', required: true },
      { id: 'm-hail-4', label: 'Cell damage observed', unit: '-', type: 'boolean', required: true },
      { id: 'm-hail-5', label: 'Pmax before hail', unit: 'W', type: 'number', required: true },
      { id: 'm-hail-6', label: 'Pmax after hail', unit: 'W', type: 'number', required: false, autoFillFrom: 'pmax' },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.18',
    code: 'MQT 10.18',
    name: 'Bypass Diode Thermal Test',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.18',
    category: 'electrical',
    duration: '3h',
    sequence: 18,
    critical: false,
    description: 'Test of bypass diode thermal performance under forward current conditions per IEC 61215-2 cl 4.18.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.18-001',
    revision: '01',
    equipment: ['Solar simulator or flasher', 'Thermocouple on JB', 'IR camera', 'Shade cloth'],
    testConditions: [
      { label: 'Irradiance', value: '1000', unit: 'W/m²', source: 'IEC 61215-2:2021 cl 4.18' },
      { label: 'Exposure duration', value: '1', unit: 'h per diode', source: 'IEC 61215-2:2021 cl 4.18' },
    ],
    acceptanceCriteria: [
      { id: 'ac-bd-1', parameter: 'Bypass diode temp rise', operator: 'lte', limit: '30°C above ambient', limitValue: 30, unit: '°C', critical: true, description: 'Diode temperature rise ≤ 30°C above ambient' },
      { id: 'ac-bd-2', parameter: 'Diode failure', operator: 'manual', limit: 'No failure', unit: '-', critical: true, description: 'No bypass diode failure during test' },
    ],
    measurements: [
      { id: 'm-bd-1', label: 'Bypass diode count', unit: '-', type: 'number', required: true },
      { id: 'm-bd-2', label: 'Max diode temp rise (ΔT)', unit: '°C', type: 'number', required: true, criterionId: 'ac-bd-1' },
      { id: 'm-bd-3', label: 'Ambient temperature', unit: '°C', type: 'number', required: true },
      { id: 'm-bd-4', label: 'Diode failure observed', unit: '-', type: 'boolean', required: true },
    ],
    hasIVCurve: false,
  },

  {
    id: 'mqt10.19',
    code: 'MQT 10.19',
    name: 'EL Imaging',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.19',
    category: 'visual',
    duration: '1h',
    sequence: 19,
    critical: false,
    description: 'Electroluminescence imaging to detect cell cracks, inactive cell areas, and soldering defects.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.19-001',
    revision: '01',
    equipment: ['EL camera (Si-CCD or InGaAs, 900–1200 nm)', 'DC power supply (Isc injection)', 'Dark enclosure'],
    testConditions: [
      { label: 'Injection current', value: 'Isc (module)', unit: 'A', source: 'IEC 61215-2:2021 cl 4.19' },
      { label: 'Integration time', value: 'As required', unit: 's', source: 'IEC 61215-2:2021 cl 4.19' },
    ],
    acceptanceCriteria: [
      { id: 'ac-el-1', parameter: 'Dark areas / inactive cells', operator: 'manual', limit: 'None > 2% cell area', unit: '-', critical: false, description: 'No dark inactive areas exceeding 2% of individual cell area' },
      { id: 'ac-el-2', parameter: 'Cell cracks', operator: 'manual', limit: 'No electrically active cracks', unit: '-', critical: true, description: 'No cracks causing electrical disconnection' },
    ],
    measurements: [
      { id: 'm-el-1', label: 'Inactive cell areas detected', unit: '-', type: 'boolean', required: true, criterionId: 'ac-el-1' },
      { id: 'm-el-2', label: 'Cell cracks detected', unit: '-', type: 'boolean', required: true, criterionId: 'ac-el-2' },
      { id: 'm-el-3', label: 'Number of cracked cells', unit: 'count', type: 'number', required: false },
      { id: 'm-el-4', label: 'Injection current used', unit: 'A', type: 'number', required: true },
    ],
    rawDataConfig: {
      type: 'el_image',
      description: 'EL image file(s)',
      acceptedFormats: ['.jpg', '.jpeg', '.png', '.tiff', '.tif'],
      columnMapping: {},
    },
    hasIVCurve: false,
    notes: 'Capture EL images before and after each stress sequence for comparison.',
  },

  {
    id: 'mqt10.20',
    code: 'MQT 10.20',
    name: 'Stabilization',
    standard: 'IEC 61215',
    standardYear: '2021',
    clause: '4.20',
    category: 'electrical',
    duration: '4h',
    sequence: 20,
    critical: false,
    description: 'Light or dark soaking to reach stable output power before and/or after stress sequences.',
    documentFormatNumber: 'SLX-FMT-61215-MQT10.20-001',
    revision: '01',
    equipment: ['Flash tester', 'Solar simulator or outdoor setup'],
    testConditions: [
      { label: 'Light soaking irradiance', value: '800–1000', unit: 'W/m²', source: 'IEC 61215-2:2021 cl 4.20' },
      { label: 'Stability criterion', value: '±0.5% change per measurement', unit: '%', source: 'IEC 61215-2:2021 cl 4.20' },
    ],
    acceptanceCriteria: [
      { id: 'ac-stab-1', parameter: 'Pmax stability', operator: 'lte', limit: '±3% of initial value', unit: '%', critical: false, description: 'Stabilized Pmax within ±3% of initial measured value' },
    ],
    measurements: [
      { id: 'm-stab-1', label: 'Initial Pmax', unit: 'W', type: 'number', required: true },
      { id: 'm-stab-2', label: 'Stabilized Pmax', unit: 'W', type: 'number', required: true, autoFillFrom: 'pmax' },
      { id: 'm-stab-3', label: 'Pmax change', unit: '%', type: 'number', required: true, criterionId: 'ac-stab-1' },
      { id: 'm-stab-4', label: 'Light soaking duration', unit: 'h', type: 'number', required: true },
    ],
    rawDataConfig: {
      type: 'flasher_iv',
      description: 'Flash tester CSV',
      acceptedFormats: ['.csv', '.xlsx'],
      columnMapping: { voltage: ['V', 'Voltage'], current: ['I', 'Current'], pmax: ['Pmax'], voc: ['Voc'], isc: ['Isc'] },
    },
    hasIVCurve: true,
  },
]
